# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kzj67GDaCC6RfIM99HcqAw8yKJOBt_zb
"""

import streamlit as st
import torch
import torch.nn as nn
from torchvision import models, transforms
from PIL import Image
import os

# --- 1. CONFIGURACION DE LA PAGINA ---
st.set_page_config(
    page_title="IA Detector de Aves PRO",
    layout="centered"
)

st.title("Clasificador de Aves CUB-200 (PRO)")
st.markdown("""
Esta aplicación utiliza una red **EfficientNetV2-S** entrenada con imágenes de alta resolución (448px)
para identificar 200 especies de aves con alta precisión.
""")

# --- 2. DEFINIR LA ARQUITECTURA DEL MODELO ---
# Debe ser exactamente igual a la que usamos en el entrenamiento en Colab
def build_model(num_classes=200):
    # Cargamos la estructura de EfficientNetV2-S
    model = models.efficientnet_v2_s(weights=None)

    # Reconstruimos la "cabeza" (clasificador) que personalizamos
    model.classifier[1] = nn.Sequential(
        nn.Linear(model.classifier[1].in_features, 512),
        nn.ReLU(),
        nn.Dropout(0.4),
        nn.Linear(512, num_classes)
    )
    return model

# --- 3. CARGA DE RECURSOS (CACHED) ---
@st.cache_resource
def load_resources():
    # A. Cargar y limpiar nombres del archivo classes.txt original
    # Formato esperado: "1 001.Black_footed_Albatross"
    try:
        with open("classes.txt", "r") as f:
            class_names = []
            for line in f:
                if line.strip():
                    # Separamos por espacio y luego por punto
                    # "1 001.Black_footed_Albatross" -> "Black_footed_Albatross"
                    name_part = line.strip().split(' ')[1].split('.')[1]
                    # Quitamos guiones bajos -> "Black footed Albatross"
                    clean_name = name_part.replace('_', ' ')
                    class_names.append(clean_name)
    except Exception as e:
        st.error(f"Error al cargar classes.txt: {e}")
        return None, None, None

    # B. Configurar dispositivo (GPU si está disponible, si no CPU)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # C. Cargar el modelo
    model = build_model(num_classes=200)
    try:
        # Cargamos los pesos guardados (modelo_aves_PRO.pth)
        model.load_state_dict(torch.load("modelo_aves_PRO.pth", map_location=device))
        model.to(device)
        model.eval() # Modo evaluación (importante para Dropout y Batchnorm)
    except Exception as e:
        st.error(f"Error al cargar el archivo .pth: {e}")
        return None, None, None

    return model, class_names, device

# Intentamos cargar todo al iniciar
model, class_names, device = load_resources()

# --- 4. FUNCION DE PREDICCION ---
def predict(image):
    # Transformaciones idénticas a las de Test en el entrenamiento
    transform = transforms.Compose([
        transforms.Resize((448, 448)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])

    # Preparamos la imagen (añadimos dimensión de batch)
    image_tensor = transform(image).unsqueeze(0).to(device)

    with torch.no_grad():
        outputs = model(image_tensor)
        # Convertimos salidas a probabilidades (Softmax)
        probabilities = torch.nn.functional.softmax(outputs[0], dim=0)
        confidence, index = torch.max(probabilities, 0)

    return class_names[index.item()], confidence.item()

# --- 5. INTERFAZ DE USUARIO (UI) ---
uploaded_file = st.file_uploader("Sube una foto de un ave...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    # Mostrar la imagen subida
    image = Image.open(uploaded_file).convert('RGB')
    st.image(image, caption='Imagen seleccionada', use_container_width=True)

    # Botón para predecir
    if st.button('Identificar Ave'):
        if model is not None:
            with st.spinner('La IA está analizando los detalles del plumaje...'):
                nombre, confianza = predict(image)

                # Mostrar resultado con estilo
                st.subheader(f"Resultado: **{nombre}**")

                # Barra de progreso para la confianza
                st.write(f"Confianza: {confianza*100:.2f}%")
                st.progress(confianza)

                if confianza < 0.40:
                    st.warning("La confianza es baja. Asegúrate de que el ave se vea clara y centrada.")
        else:
            st.error("El modelo no se cargó correctamente. Revisa los archivos en tu repositorio.")

st.sidebar.info("Proyecto CUB-200 Bird Detection - Entrenado con PyTorch")